version: "3"

services:
  database:
    image: postgres
    container_name: labs_service_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=labs

  labs-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: php bin/console server:run 0.0.0.0:8088
    ports:
      - "8088:8088"
    depends_on:
      - database
