version: "3"

services:
  database:
    image: postgres
    container_name: labs_service_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=labs

  labs-service:
    build:
      context: .
      dockerfile: Dockerfile
    # command: "php bin/console doctrine:migrations:migrate; php bin/console server:run 0.0.0.0:8088"
    volumes:
      - ".:/app"
    ports:
      - "8088:8088"
    depends_on:
      - database

  mq:
    image: rabbitmq:3.9.10-management-alpine
    container_name: mq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=vhost
